# Generated by Django 5.0.3 on 2024-03-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.IntegerField(max_length=12)),
                ('jet', models.TextField()),
                ('budget', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
